changelog = {
		1140000: ("1.14.0.0", "31 January 2016", [
			" Please update your Image Pack",
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" How to Build your own Domination Map",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1130100: ("1.13.1.0", "14 August 2015", [
			" Please update your Image Pack",
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			"How to Build your own Domination Map",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1130000: ("1.13.0.0", "14 August 2015", [
			" Please update your Image Pack",
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			"How to Build your own Domination Map",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1120700: ("1.12.7.0", "7 June 2015", [
			" Please update your Image Pack",
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1110000: ("1.11.0.0", "10 January 2015", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1100000: ("1.10.0.0", "03 September 2014", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1090000: ("1.9.0.0", "01 August 2014", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1080000: ("1.8.0.0", "20 July 2014", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1070000: ("1.7.0.0", "01 June 2014", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			])
}
