changelog = {
		1126000: ("1.12.6.0", "10 June 2015", [
			"Please update your Image Pack",
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1110000: ("1.11.0.0", "10 January 2015", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1100000: ("1.10.0.0", "03 September 2014", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1090000: ("1.9.0.0", "01 August 2014", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1080000: ("1.8.0.0", "20 July 2014", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			]),
		1070000: ("1.7.0.0", "01 June 2014", [
			" Game Documents | Playing Mage Wars on OCTGN",
			" Game Documents | OCTGN Apprentice Mode",
			" Game Documents | Keyboard Shortcut Mappings",
			" Game Documents | Mage Wars Complete Codex",
			" Game Documents | Mage Wars Condition Markers",
			" Game Documents | Spellbook Builder Install Help",
			" Game Documents | ChangeLog",
			])
}
